// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Service {
    #[prost(string, tag="1")]
    pub schema: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
